### ISSUE TITLE
Option to disable rounded corners

### ISSUE THREAD

**Issue by LordMZTE** [gabm/Satty#136]
It seems like there has been a misunderstanding regarding the recently merged PR #134. The PR initially proposed an option for rounded corners. It was then requested that this option be on by default, but remain available to disable the feature. Instead, the option was removed entirely, leaving no option to disable rounded corners. I think it would make sense to revise this PR to be more similar to its initial proposal (commit dc25482428febbabfbac58f81447a42419c17b82), but with the default value set to `true`.

**Comment by schaumtier** [comment]
@gabm wrote "without option to switch back", so i thought an additional switch or option is not desired

**Comment by LordMZTE** [comment]
True, seems like I misunderstood myself. It would still be great to have the option to disable this, because I personally dislike rounded corners. I can open a PR adding an option, but let's wait for gabm's approval first.

**Comment by gabm** [comment]
I thought that this had no real downsides - and I like the result of @schaumtier PR more. But if there is controversy around this - lets (re-)add an option to disable this.

Instead of enable/disable, we could also allow an integer that specifies the roundness, going from 0 (rect) to higher (increasingly more rounded rect).

**Comment by schaumtier** [comment]
okay i can create another PR with that funtionality (with the roundness integer)

**Comment by gabm** [comment]
I believe this has been merged and released as v0.15.0.
